apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7wxw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7wxw
    app.kubernetes.io/part-of: dc-metro-map
  name: devfile-sample-7wxw
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7wxw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7wxw
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/shbose-tenant/dc-metro-map/devfile-sample-7wxw@sha256:2f4b2f7d0d7ff8b5bf0bfe567c89847389ab1379b299fbf2202e1416c2ca8be0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
